name: Build and Publish Jammy Stacks

on:
  pull_request:
    branches: [ 'main' ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: "ubuntu-24.04-arm"
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Build and Push
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          docker run -d -p 5000:5000 --name registry registry:2.7
          echo '{"insecure-registries" : "localhost:5000" }'  | \
            sudo tee /etc/docker/daemon.json
          echo -e '\n[[registry]]\nlocation = "localhost:5000"\ninsecure = true\n' >> \
            "$HOME/.config/containers/registries.conf"
          cat "$HOME/.config/containers/registries.conf"
          skopeo login ghcr.io -u gh-action -p "$GITHUB_TOKEN"
          go run .
